// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Input: typeof import('./core/components/basic/Input.vue')['default']
    LeftAside: typeof import('./pages/worksheet/components/leftAside.vue')['default']
    MidAside: typeof import('./pages/worksheet/components/midAside.vue')['default']
    Radio: typeof import('./core/components/basic/Radio.vue')['default']
    RawDisplayer: typeof import('./pages/worksheet/components/rawDisplayer.vue')['default']
    Renderer: typeof import('./core/renderer/renderer.vue')['default']
    RightAside: typeof import('./pages/worksheet/components/rightAside.vue')['default']
    Select: typeof import('./core/components/basic/Select.vue')['default']
    Switch: typeof import('./core/components/basic/Switch.vue')['default']
  }
}

export { }
